# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get("http://127.0.0.1:8000/#/")
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  

  def test_search_button(self):
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("bear")
    time.sleep(2)
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)

 
  def test_search_accourding_category(self):
    self.driver.find_element(By.NAME, "q")
    self.driver.find_element(By.NAME, "q").send_keys("toys")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    time.sleep(3)

    print(self.driver.page_source) 

  def test_add_item_to_card(self):
    # time.sleep(3)
    self.driver.find_element(By.NAME, "q")
    self.driver.find_element(By.NAME, "q").send_keys("gloves")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "#root > div > main > div > div > div > div:nth-child(4) > div > div > a > div > strong").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR,"#root > div > main > div > div > div:nth-child(1) > div.col > div > div > div:nth-child(4) > button").click()
    time.sleep(2)
    assert "Shopping Cart" in self.driver.page_source

  def test_card(self):
    element = self.driver.find_element(By.CSS_SELECTOR, ".ms-auto > .nav-link")
    element.click()

  def test_checkout_card(self):
    self.driver.find_element(By.NAME, "q")
    self.driver.find_element(By.NAME, "q").send_keys("gloves")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "#root > div > main > div > div > div > div:nth-child(4) > div > div > a > div > strong").click()
    # time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR,"#root > div > main > div > div > div:nth-child(1) > div.col > div > div > div:nth-child(4) > button").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, '#root > header > nav > div > a > img').click()
    time.sleep(5)   
    self.driver.find_element(By.CSS_SELECTOR, ".w-100").click()   
    time.sleep(3)
    self.driver.find_element(By.ID, "address").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "address").send_keys("Israel")
    time.sleep(3)
    self.driver.find_element(By.ID, "city").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "city").send_keys("Rahat")
    time.sleep(3)
    self.driver.find_element(By.ID, "postalCode").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "postalCode").send_keys("12345")
    time.sleep(3)
    self.driver.find_element(By.ID, "country").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "country").send_keys("Israel")
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".my-3").click()
    time.sleep(3)
  

